/*
 * Copyright 2020 Sergei Sovik <sergeisovik@yahoo.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use strict";

export const ISO639_1 = {
	"ab": { "name": "Abkhazian", "native": "аҧсуа бызшәа, аҧсшәа" },
	"aa": { "name": "Afar", "native": "Afaraf" },
	"af": { "name": "Afrikaans", "native": "Afrikaans" },
	"ak": { "name": "Akan", "native": "Akan" },
	"sq": { "name": "Albanian", "native": "Shqip" },
	"am": { "name": "Amharic", "native": "አማርኛ" },
	"ar": { "name": "Arabic", "native": "العربية" },
	"an": { "name": "Aragonese", "native": "aragonés" },
	"hy": { "name": "Armenian", "native": "Հայերեն" },
	"as": { "name": "Assamese", "native": "অসমীয়া" },
	"av": { "name": "Avaric", "native": "авар мацӀ, магӀарул мацӀ" },
	"ae": { "name": "Avestan", "native": "avesta" },
	"ay": { "name": "Aymara", "native": "aymar aru" },
	"az": { "name": "Azerbaijani", "native": "azərbaycan dili" },
	"bm": { "name": "Bambara", "native": "bamanankan" },
	"ba": { "name": "Bashkir", "native": "башҡорт теле" },
	"eu": { "name": "Basque", "native": "euskara, euskera" },
	"be": { "name": "Belarusian", "native": "беларуская мова" },
	"bn": { "name": "Bengali", "native": "বাংলা" },
	"bh": { "name": "Bihari languages", "native": "भोजपुरी" },
	"bi": { "name": "Bislama", "native": "Bislama" },
	"bs": { "name": "Bosnian", "native": "bosanski jezik" },
	"br": { "name": "Breton", "native": "brezhoneg" },
	"bg": { "name": "Bulgarian", "native": "български език" },
	"my": { "name": "Burmese", "native": "ဗမာစာ" },
	"ca": { "name": "Catalan, Valencian", "native": "català, valencià" },
	"ch": { "name": "Chamorro", "native": "Chamoru" },
	"ce": { "name": "Chechen", "native": "нохчийн мотт" },
	"ny": { "name": "Chichewa, Chewa, Nyanja", "native": "chiCheŵa, chinyanja" },
	"zh": { "name": "Chinese", "native": "中文 (Zhōngwén), 汉语, 漢語" },
	"cv": { "name": "Chuvash", "native": "чӑваш чӗлхи" },
	"kw": { "name": "Cornish", "native": "Kernewek" },
	"co": { "name": "Corsican", "native": "corsu, lingua corsa" },
	"cr": { "name": "Cree", "native": "ᓀᐦᐃᔭᐍᐏᐣ" },
	"hr": { "name": "Croatian", "native": "hrvatski jezik" },
	"cs": { "name": "Czech", "native": "čeština, český jazyk" },
	"da": { "name": "Danish", "native": "dansk" },
	"dv": { "name": "Divehi, Dhivehi, Maldivian", "native": "ދިވެހި" },
	"nl": { "name": "Dutch, Flemish", "native": "Nederlands, Vlaams" },
	"dz": { "name": "Dzongkha", "native": "རྫོང་ཁ" },
	"en": { "name": "English", "native": "English" },
	"eo": { "name": "Esperanto", "native": "Esperanto" },
	"et": { "name": "Estonian", "native": "eesti, eesti keel" },
	"ee": { "name": "Ewe", "native": "Eʋegbe" },
	"fo": { "name": "Faroese", "native": "føroyskt" },
	"fj": { "name": "Fijian", "native": "vosa Vakaviti" },
	"fi": { "name": "Finnish", "native": "suomi, suomen kieli" },
	"fr": { "name": "French", "native": "français, langue française" },
	"ff": { "name": "Fulah", "native": "Fulfulde, Pulaar, Pular" },
	"gl": { "name": "Galician", "native": "Galego" },
	"ka": { "name": "Georgian", "native": "ქართული" },
	"de": { "name": "German", "native": "Deutsch" },
	"el": { "name": "Greek, Modern (1453-)", "native": "ελληνικά" },
	"gn": { "name": "Guarani", "native": "Avañe'ẽ" },
	"gu": { "name": "Gujarati", "native": "ગુજરાતી" },
	"ht": { "name": "Haitian, Haitian Creole", "native": "Kreyòl ayisyen" },
	"ha": { "name": "Hausa", "native": "(Hausa) هَوُسَ" },
	"he": { "name": "Hebrew", "native": "עברית" },
	"hz": { "name": "Herero", "native": "Otjiherero" },
	"hi": { "name": "Hindi", "native": "हिन्दी, हिंदी" },
	"ho": { "name": "Hiri Motu", "native": "Hiri Motu" },
	"hu": { "name": "Hungarian", "native": "magyar" },
	"ia": { "name": "Interlingua (International Auxiliary Language Association)", "native": "Interlingua" },
	"id": { "name": "Indonesian", "native": "Bahasa Indonesia" },
	"ie": { "name": "Interlingue, Occidental", "native": "(originally:) Occidental, (after WWII:) Interlingue" },
	"ga": { "name": "Irish", "native": "Gaeilge" },
	"ig": { "name": "Igbo", "native": "Asụsụ Igbo" },
	"ik": { "name": "Inupiaq", "native": "Iñupiaq, Iñupiatun" },
	"io": { "name": "Ido", "native": "Ido" },
	"is": { "name": "Icelandic", "native": "Íslenska" },
	"it": { "name": "Italian", "native": "Italiano" },
	"iu": { "name": "Inuktitut", "native": "ᐃᓄᒃᑎᑐᑦ" },
	"ja": { "name": "Japanese", "native": "日本語 (にほんご)" },
	"jv": { "name": "Javanese", "native": "ꦧꦱꦗꦮ, Basa Jawa" },
	"kl": { "name": "Kalaallisut, Greenlandic", "native": "kalaallisut, kalaallit oqaasii" },
	"kn": { "name": "Kannada", "native": "ಕನ್ನಡ" },
	"kr": { "name": "Kanuri", "native": "Kanuri" },
	"ks": { "name": "Kashmiri", "native": "कश्मीरी, كشميري‎" },
	"kk": { "name": "Kazakh", "native": "қазақ тілі" },
	"km": { "name": "Central Khmer", "native": "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ" },
	"ki": { "name": "Kikuyu, Gikuyu", "native": "Gĩkũyũ" },
	"rw": { "name": "Kinyarwanda", "native": "Ikinyarwanda" },
	"ky": { "name": "Kirghiz, Kyrgyz", "native": "Кыргызча, Кыргыз тили" },
	"kv": { "name": "Komi", "native": "коми кыв" },
	"kg": { "name": "Kongo", "native": "Kikongo" },
	"ko": { "name": "Korean", "native": "한국어" },
	"ku": { "name": "Kurdish", "native": "Kurdî, کوردی‎" },
	"kj": { "name": "Kuanyama, Kwanyama", "native": "Kuanyama" },
	"la": { "name": "Latin", "native": "latine, lingua latina" },
	"lb": { "name": "Luxembourgish, Letzeburgesch", "native": "Lëtzebuergesch" },
	"lg": { "name": "Ganda", "native": "Luganda" },
	"li": { "name": "Limburgan, Limburger, Limburgish", "native": "Limburgs" },
	"ln": { "name": "Lingala", "native": "Lingála" },
	"lo": { "name": "Lao", "native": "ພາສາລາວ" },
	"lt": { "name": "Lithuanian", "native": "lietuvių kalba" },
	"lu": { "name": "Luba-Katanga", "native": "Kiluba" },
	"lv": { "name": "Latvian", "native": "latviešu valoda" },
	"gv": { "name": "Manx", "native": "Gaelg, Gailck" },
	"mk": { "name": "Macedonian", "native": "македонски јазик" },
	"mg": { "name": "Malagasy", "native": "fiteny malagasy" },
	"ms": { "name": "Malay", "native": "Bahasa Melayu, بهاس ملايو‎" },
	"ml": { "name": "Malayalam", "native": "മലയാളം" },
	"mt": { "name": "Maltese", "native": "Malti" },
	"mi": { "name": "Maori", "native": "te reo Māori" },
	"mr": { "name": "Marathi", "native": "मराठी" },
	"mh": { "name": "Marshallese", "native": "Kajin M̧ajeļ" },
	"mn": { "name": "Mongolian", "native": "Монгол хэл" },
	"na": { "name": "Nauru", "native": "Dorerin Naoero" },
	"nv": { "name": "Navajo, Navaho", "native": "Diné bizaad" },
	"nd": { "name": "North Ndebele", "native": "isiNdebele" },
	"ne": { "name": "Nepali", "native": "नेपाली" },
	"ng": { "name": "Ndonga", "native": "Owambo" },
	"nb": { "name": "Norwegian Bokmål", "native": "Norsk Bokmål" },
	"nn": { "name": "Norwegian Nynorsk", "native": "Norsk Nynorsk" },
	"no": { "name": "Norwegian", "native": "Norsk" },
	"ii": { "name": "Sichuan Yi, Nuosu", "native": "ꆈꌠ꒿ Nuosuhxop" },
	"nr": { "name": "South Ndebele", "native": "isiNdebele" },
	"oc": { "name": "Occitan", "native": "occitan, lenga d'òc" },
	"oj": { "name": "Ojibwa", "native": "ᐊᓂᔑᓈᐯᒧᐎᓐ" },
	"cu": { "name": "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic", "native": "ѩзыкъ словѣньскъ" },
	"om": { "name": "Oromo", "native": "Afaan Oromoo" },
	"or": { "name": "Oriya", "native": "ଓଡ଼ିଆ" },
	"os": { "name": "Ossetian, Ossetic", "native": "ирон æвзаг" },
	"pa": { "name": "Punjabi, Panjabi", "native": "ਪੰਜਾਬੀ, پنجابی‎" },
	"pi": { "name": "Pali", "native": "पालि, पाळि" },
	"fa": { "name": "Persian", "native": "فارسی" },
	"pl": { "name": "Polish", "native": "język polski, polszczyzna" },
	"ps": { "name": "Pashto, Pushto", "native": "پښتو" },
	"pt": { "name": "Portuguese", "native": "Português" },
	"qu": { "name": "Quechua", "native": "Runa Simi, Kichwa" },
	"rm": { "name": "Romansh", "native": "Rumantsch Grischun" },
	"rn": { "name": "Rundi", "native": "Ikirundi" },
	"ro": { "name": "Romanian, Moldavian, Moldovan", "native": "Română" },
	"ru": { "name": "Russian", "native": "русский" },
	"sa": { "name": "Sanskrit", "native": "संस्कृतम्" },
	"sc": { "name": "Sardinian", "native": "sardu" },
	"sd": { "name": "Sindhi", "native": "सिन्धी, سنڌي، سندھی‎" },
	"se": { "name": "Northern Sami", "native": "Davvisámegiella" },
	"sm": { "name": "Samoan", "native": "gagana fa'a Samoa" },
	"sg": { "name": "Sango", "native": "yângâ tî sängö" },
	"sr": { "name": "Serbian", "native": "српски језик" },
	"gd": { "name": "Gaelic, Scottish Gaelic", "native": "Gàidhlig" },
	"sn": { "name": "Shona", "native": "chiShona" },
	"si": { "name": "Sinhala, Sinhalese", "native": "සිංහල" },
	"sk": { "name": "Slovak", "native": "Slovenčina, Slovenský Jazyk" },
	"sl": { "name": "Slovenian", "native": "Slovenski Jezik, Slovenščina" },
	"so": { "name": "Somali", "native": "Soomaaliga, af Soomaali" },
	"st": { "name": "Southern Sotho", "native": "Sesotho" },
	"es": { "name": "Spanish, Castilian", "native": "Español" },
	"su": { "name": "Sundanese", "native": "Basa Sunda" },
	"sw": { "name": "Swahili", "native": "Kiswahili" },
	"ss": { "name": "Swati", "native": "SiSwati" },
	"sv": { "name": "Swedish", "native": "Svenska" },
	"ta": { "name": "Tamil", "native": "தமிழ்" },
	"te": { "name": "Telugu", "native": "తెలుగు" },
	"tg": { "name": "Tajik", "native": "тоҷикӣ, toçikī, تاجیکی‎" },
	"th": { "name": "Thai", "native": "ไทย" },
	"ti": { "name": "Tigrinya", "native": "ትግርኛ" },
	"bo": { "name": "Tibetan", "native": "བོད་ཡིག" },
	"tk": { "name": "Turkmen", "native": "Türkmen, Түркмен" },
	"tl": { "name": "Tagalog", "native": "Wikang Tagalog" },
	"tn": { "name": "Tswana", "native": "Setswana" },
	"to": { "name": "Tonga (Tonga Islands)", "native": "Faka Tonga" },
	"tr": { "name": "Turkish", "native": "Türkçe" },
	"ts": { "name": "Tsonga", "native": "Xitsonga" },
	"tt": { "name": "Tatar", "native": "татар теле, tatar tele" },
	"tw": { "name": "Twi", "native": "Twi" },
	"ty": { "name": "Tahitian", "native": "Reo Tahiti" },
	"ug": { "name": "Uighur, Uyghur", "native": "ئۇيغۇرچە‎, Uyghurche" },
	"uk": { "name": "Ukrainian", "native": "Українська" },
	"ur": { "name": "Urdu", "native": "اردو" },
	"uz": { "name": "Uzbek", "native": "Oʻzbek, Ўзбек, أۇزبېك‎" },
	"ve": { "name": "Venda", "native": "Tshivenḓa" },
	"vi": { "name": "Vietnamese", "native": "Tiếng Việt" },
	"vo": { "name": "Volapük", "native": "Volapük" },
	"wa": { "name": "Walloon", "native": "Walon" },
	"cy": { "name": "Welsh", "native": "Cymraeg" },
	"wo": { "name": "Wolof", "native": "Wollof" },
	"fy": { "name": "Western Frisian", "native": "Frysk" },
	"xh": { "name": "Xhosa", "native": "isiXhosa" },
	"yi": { "name": "Yiddish", "native": "ייִדיש" },
	"yo": { "name": "Yoruba", "native": "Yorùbá" },
	"za": { "name": "Zhuang, Chuang", "native": "Saɯ cueŋƅ, Saw cuengh" },
	"zu": { "name": "Zulu", "native": "isiZulu" },
};
